name: CD - Deploy to Google Cloud Run

on:
  workflow_run:
    workflows: ["CI"]  # Pastikan nama workflow CI sesuai dengan file CI Anda, misalnya "CI"
    types:
      - completed

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest

    # Deploy hanya jika workflow CI berhasil
    if: github.event.workflow_run.conclusion == 'success'

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      # Step 3: Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # Step 4: Build and Push Docker Image
      - name: Build and Push Docker image
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/expense-app .

      # Step 5: Deploy the application to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy expense-app \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/expense-app \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated

            